-- MySQL Script generated by MySQL Workbench
-- 08/08/15 14:59:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hyshop
-- -----------------------------------------------------
-- 商城
DROP SCHEMA IF EXISTS `hyshop` ;

-- -----------------------------------------------------
-- Schema hyshop
--
-- 商城
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hyshop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hyshop` ;

-- -----------------------------------------------------
-- Table `hyshop`.`hy_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_category` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_category` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cat_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '分类名',
  `cat_desc` TEXT NOT NULL COMMENT '分类描述',
  `parent_id` INT NOT NULL DEFAULT 0 COMMENT '父级分类',
  `is_show` TINYINT(1) NULL DEFAULT 1 COMMENT '是否显示',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = MyISAM
COMMENT = '商品分类表';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_brand` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_brand` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `brand_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '品牌名',
  `brand_desc` TEXT NOT NULL COMMENT '品牌介绍',
  `brand_url` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '品牌官网',
  `brand_img` VARCHAR(250) NOT NULL DEFAULT '' COMMENT '品牌logo',
  `is_show` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否显示',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = MyISAM
COMMENT = '商品品牌表';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_goods` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_goods` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `goods_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '商品名',
  `goods_sn` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '货号',
  `goods_price` DECIMAL(20,3) NOT NULL DEFAULT 0.00 COMMENT '销售价',
  `original_price` DECIMAL(20,3) NOT NULL DEFAULT 0.00 COMMENT '原价',
  `cost_price` DECIMAL(20,3) NOT NULL DEFAULT 0.00 COMMENT '成本价',
  `goods_stock` INT NOT NULL DEFAULT 0 COMMENT '库存',
  `goods_desc` TEXT NOT NULL COMMENT '',
  `goods_staus` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '商品状态;1:上架，0：下架',
  `is_new` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否为新品',
  `cat_id` INT NOT NULL DEFAULT 0 COMMENT '',
  `bid` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `cat_id` (`cat_id` ASC)  COMMENT '',
  INDEX `bid` (`bid` ASC)  COMMENT '')
ENGINE = MyISAM
COMMENT = '商品主表';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_goods_pic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_goods_pic` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_goods_pic` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `pic_url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '图片地址',
  `is_default` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否默认',
  `gid` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `gid` (`gid` ASC)  COMMENT '')
ENGINE = MyISAM
COMMENT = '商品图片表';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_ad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_ad` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_ad` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ad_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '',
  `ad_path` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '图片路径',
  `ad_url` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '网络地址',
  `ad_desc` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = MyISAM
COMMENT = '广告';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_admin_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_admin_user` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_admin_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` CHAR(20) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` CHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  `email` CHAR(80) NOT NULL DEFAULT '' COMMENT '邮箱地址',
  `add_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加时间',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = MyISAM
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_user` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_user` (
  `id` INT NOT NULL COMMENT '',
  `username` CHAR(30) NOT NULL DEFAULT '' COMMENT '帐号',
  `password` CHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  `email` VARCHAR(150) NOT NULL DEFAULT '' COMMENT '邮箱',
  `moblic` INT NOT NULL DEFAULT 0 COMMENT '手机',
  `sex` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '性别，1：男，2：女，0：保密',
  `reg_time` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = MyISAM
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_user_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_user_address` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_user_address` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `province` INT NOT NULL DEFAULT 0 COMMENT '省份',
  `city` INT NOT NULL DEFAULT 0 COMMENT '城市',
  `address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '街道地址',
  `receipt_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '收货人名字',
  `mobile` INT NOT NULL DEFAULT 0 COMMENT '收货人手机',
  `code` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '邮编',
  `uid` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '')
ENGINE = MyISAM
COMMENT = '用户地址表';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_orders` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_orders` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `order_sn` CHAR(20) NOT NULL DEFAULT '' COMMENT '订单编号',
  `order_staus` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '订单状态；0：未付款，1：已付款，2：系统确认，3：发货，4：确认收货，5：11：取消，12：过期，13：退货',
  `order_time` INT NOT NULL DEFAULT 0 COMMENT '订单时间',
  `order_price` DECIMAL(20,3) NOT NULL DEFAULT 0.00 COMMENT '订单总价',
  `order_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '订单留言',
  `order_type` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '支付方式，1：微信支付，2：支付宝支付，3：网银在线',
  `delivery` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '配送方式，1：顺丰，2：圆通',
  `uid` INT NOT NULL DEFAULT 0 COMMENT '用户id',
  `order_cost` DECIMAL(20,3) NOT NULL DEFAULT 0.00 COMMENT '成本总价',
  `preferential_price` DECIMAL(20,3) NOT NULL DEFAULT 0.00 COMMENT '优惠价钱',
  `address_id` INT NOT NULL DEFAULT 0 COMMENT '地址id',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '',
  INDEX `address_id` (`address_id` ASC)  COMMENT '')
ENGINE = MyISAM
COMMENT = '订单表';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_orders_goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_orders_goods` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_orders_goods` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `unit_price` DECIMAL(20,3) NOT NULL DEFAULT 0.00 COMMENT '单价',
  `count_price` DECIMAL(20,3) NOT NULL DEFAULT 0.00 COMMENT '总价',
  `oid` INT NOT NULL DEFAULT 0 COMMENT '订单id',
  `gid` INT NOT NULL DEFAULT 0 COMMENT '商品id',
  `nunber` INT NOT NULL DEFAULT 0 COMMENT '商品数量',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `oid` (`oid` ASC)  COMMENT '',
  INDEX `gid` (`gid` ASC)  COMMENT '')
ENGINE = MyISAM
COMMENT = '订单商品表';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_user_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_user_record` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_user_record` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `record_time` INT NOT NULL DEFAULT 0 COMMENT '浏览时间',
  `uid` INT NOT NULL COMMENT '',
  `gid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '',
  INDEX `gid` (`gid` ASC)  COMMENT '')
ENGINE = MyISAM
COMMENT = '用户浏览记录';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_cart` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_cart` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `add_time` INT NOT NULL DEFAULT 0 COMMENT '添加时间',
  `cart_staus` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '购物车状态，1：可以购买，0：失效',
  `uid` INT NOT NULL COMMENT '',
  `gid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '',
  INDEX `fk_hy_cart_hy_goods1_idx` (`gid` ASC)  COMMENT '')
ENGINE = MyISAM
COMMENT = '购物车表';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_comment` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_comment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '评论内容',
  `IPaddress` INT NOT NULL DEFAULT 0 COMMENT 'IP地址',
  `add_time` INT NOT NULL DEFAULT 0 COMMENT '评论时间',
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '评论状态，1：显示，0：隐藏',
  `gid` INT NOT NULL COMMENT '',
  `uid` INT NOT NULL COMMENT '',
  `cid` INT NOT NULL DEFAULT 0 COMMENT '回复id，0：没有回复',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `gid` (`gid` ASC)  COMMENT '',
  INDEX `uid` (`uid` ASC)  COMMENT '',
  INDEX `cid` (`cid` ASC)  COMMENT '')
ENGINE = MyISAM
COMMENT = '商品评论表';


-- -----------------------------------------------------
-- Table `hyshop`.`hy_collect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyshop`.`hy_collect` ;

CREATE TABLE IF NOT EXISTS `hyshop`.`hy_collect` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `add_time` INT NOT NULL DEFAULT 0 COMMENT '添加时间',
  `is_attention` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否为收藏状态；1：是，0：否',
  `uid` INT NOT NULL DEFAULT 0 COMMENT '用户id',
  `gid` INT NOT NULL DEFAULT 0 COMMENT '商品id',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_hy_collect_hy_user1_idx` (`uid` ASC)  COMMENT '',
  INDEX `fk_hy_collect_hy_goods1_idx` (`gid` ASC)  COMMENT '')
ENGINE = MyISAM
COMMENT = '收藏表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
